os:
- linux

language:
- java

jdk:
- oraclejdk8

sudo: false

before_install:
- jdk_switcher use oraclejdk8
- java -version

script:
- java -jar target/split-ingest-pdf.jar --help
- mvn sonar:sonar -Dsonar.organization=viniciuslj-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$sonarLogin -Dsonar.projectKey=split-ingest-pdf -Dsonar.projectName=split-ingest-pdf -Dsonar.sources="src/main"

notifications:
  email: false
